image:
  file: Dockerfile
tasks:
  - name: Rails
    init: >
      gem install bundler:2.0.1 &&
      bundle install &&
      npm install -g yarn &&
      yarn install --check-files &&
      rails db:drop && rails db:create && rails db:migrate &&
      gp sync-done bundle
    command: rails s