# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: postgresql
  database: aasm_papertrail_development
  pool: 5
  username: gitpod

test:
  adapter: postgresql
  database: aasm_papertrail_test
  pool: 5
  username: gitpod